"""add_role_to_employees_and_auto_enrolled_to_enrollments

Revision ID: 44d2aecc9845
Revises: 4c9477d6108b
Create Date: 2026-01-31 02:17:49.088272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44d2aecc9845'
down_revision: Union[str, None] = '4c9477d6108b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('role', sa.String(), nullable=True))
    op.add_column('enrollments', sa.Column('auto_enrolled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'auto_enrolled')
    op.drop_column('employees', 'role')
    # ### end Alembic commands ###
